
spring:
  profiles:
    active: local
  redis:
    port: 6379

kakao:
  apiKey: "09a326b99c78cd66672fcd0d0eed4c1c"
  header: "KakaoAK "
  host: "dapi.kakao.com"
  search:
    keywordUrl: "/v2/local/search/keyword.json"
naver:
  clientId: "wNQayiR1hxZ5ZKQyarDu"
  clientSecret: "ARMXrkdwxL"
  host: "openapi.naver.com"
  search:
    local: "/v1/search/local"